### ISSUE TITLE
Almost all generators result in error

### ISSUE THREAD

**Issue by devth** [drbrain/meme#7]
Every generator except Y_U_NO results in:

```
.rvm/gems/ruby-1.9.1-p378/gems/meme_generator-1.2/lib/meme.rb:114:in `generate': undefined local variable or method `generator_name' for #<Meme:0x00000102841c18> (NameError)
```

Tried in ruby 1.9.1 and 1.9.2

**Comment by drbrain** [comment]
I fixed the error message printing so you now get an error message instead of a crash, try 1.2.1.

Ruby 1.9.1 and earlier are not supported: https://github.com/drbrain/meme/blob/master/Rakefile#L16

**Comment by devth** [comment]
Same deal on 1.9.2. Tried this on both my work macbook and my home macbook with 1.9.2 via rvm. 

```
meme PHILOSORAPTOR 'lolwtfpwned'                                                                                                                                                                                                       
~/.rvm/gems/ruby-1.9.2-p136/gems/meme_generator-1.2/lib/meme.rb:114:in `generate': undefined local variable or method `generator_name' for #<Meme:0x00000101358cf0> (NameError)
```

**Comment by drbrain** [comment]
Of course it doesn't work with 1.2, 1.2 is broken. You need to upgrade

**Comment by devth** [comment]
Ok, well nowhere does it say 1.2 was broken...I just followed directions on the README and 1.2 is the latest at http://rubygems.org/gems/meme_generator

**Comment by drbrain** [comment]
I'm sorry, my release didn't go because I was using the latest RubyGems.  Try 1.2.2 now.

Sorry for the misinformation.

**Comment by devth** [comment]
Cool, thanks. Working now :)
